// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026 Arnis Lektauers
//
// CPU-based environment lighting atlas generation.
//
#include "envLighting.h"

#include <algorithm>
#include <cmath>
#include <cstring>
#include <memory>
#include <numbers>
#include <unordered_map>

#include <spdlog/spdlog.h>

#include "core/math/random.h"
#include "envReproject.h"
#include "platform/graphics/texture.h"
#include "platform/graphics/graphicsDevice.h"

namespace visutwin::canvas
{
    // ----------------------------------------------------------------
    // Constants
    // ----------------------------------------------------------------
    static constexpr float ENV_PI = std::numbers::pi_v<float>;
    static constexpr float ENV_TWO_PI = 2.0f * ENV_PI;

    static int calcLevels(int size)
    {
        return 1 + static_cast<int>(std::floor(std::log2(std::max(size, 1))));
    }

    // ----------------------------------------------------------------
    // Required samples table for GGX (pre-calculated)
    // Matches upstream requiredSamplesGGX table
    // ----------------------------------------------------------------
    int EnvLighting::getRequiredSamplesGGX(int numSamples, int specularPower)
    {
        // Table generated by calculateRequiredSamplesGGX() in the upstream engine
        static const std::unordered_map<int, std::unordered_map<int, int>> table = {
            {16, {{2, 26}, {8, 20}, {32, 17}, {128, 16}, {512, 16}}},
            {32, {{2, 53}, {8, 40}, {32, 34}, {128, 32}, {512, 32}}},
            {128, {{2, 214}, {8, 163}, {32, 139}, {128, 130}, {512, 128}}},
            {1024, {{2, 1722}, {8, 1310}, {32, 1114}, {128, 1041}, {512, 1025}}}
        };

        auto it = table.find(numSamples);
        if (it != table.end()) {
            auto it2 = it->second.find(specularPower);
            if (it2 != it->second.end()) {
                return it2->second;
            }
        }
        return numSamples;
    }

    // ----------------------------------------------------------------
    // RGBP encoding
    // ----------------------------------------------------------------
    std::array<uint8_t, 4> EnvLighting::encodeRGBP(float r, float g, float b)
    {
        // Decode in shader: color = rgb * (-a * 7.0 + 8.0); color = color * color;
        // So encode: sqrt(color), then find 'a' such that rgb / (-a*7+8) fits in [0,1]
        const float sr = std::sqrt(std::max(r, 0.0f));
        const float sg = std::sqrt(std::max(g, 0.0f));
        const float sb = std::sqrt(std::max(b, 0.0f));

        const float maxVal = std::max({sr, sg, sb, 1.0f / 255.0f});
        const float a = std::clamp((8.0f - maxVal) / 7.0f, 0.0f, 1.0f);
        const float scale = -a * 7.0f + 8.0f;

        return {
            static_cast<uint8_t>(std::clamp(sr / scale * 255.0f + 0.5f, 0.0f, 255.0f)),
            static_cast<uint8_t>(std::clamp(sg / scale * 255.0f + 0.5f, 0.0f, 255.0f)),
            static_cast<uint8_t>(std::clamp(sb / scale * 255.0f + 0.5f, 0.0f, 255.0f)),
            static_cast<uint8_t>(std::clamp(a * 255.0f + 0.5f, 0.0f, 255.0f))
        };
    }

    // ----------------------------------------------------------------
    // Direction <-> equirectangular UV
    // Matches Metal shader toSphericalUv()
    // ----------------------------------------------------------------
    void EnvLighting::dirToEquirectUv(float x, float y, float z, float& u, float& v)
    {
        const float phi = std::atan2(x, z);         // azimuth
        const float theta = std::asin(std::clamp(y, -1.0f, 1.0f)); // elevation
        u = phi / ENV_TWO_PI + 0.5f;
        v = 1.0f - (theta / ENV_PI + 0.5f);
    }

    // Face index + UV -> 3D direction (used by generateSkyboxCubemap).
    static void faceUvToDir(int face, float u, float v, float& x, float& y, float& z)
    {
        // Convert UV [0,1] to [-1,1]
        const float sc = u * 2.0f - 1.0f;
        const float tc = v * 2.0f - 1.0f;

        switch (face) {
            case 0: x =  1.0f; y = -tc;   z = -sc;   break; // +X
            case 1: x = -1.0f; y = -tc;   z =  sc;   break; // -X
            case 2: x =  sc;   y =  1.0f; z =  tc;   break; // +Y
            case 3: x =  sc;   y = -1.0f; z = -tc;   break; // -Y
            case 4: x =  sc;   y = -tc;   z =  1.0f; break; // +Z
            case 5: x = -sc;   y = -tc;   z = -1.0f; break; // -Z
            default: x = y = z = 0.0f; break;
        }

        // Normalize
        const float len = std::sqrt(x * x + y * y + z * z);
        if (len > 0.0f) {
            x /= len;
            y /= len;
            z /= len;
        }
    }

    // ----------------------------------------------------------------
    // Hemisphere sampling
    // ----------------------------------------------------------------
    void EnvLighting::hemisphereSampleGGX(float& hx, float& hy, float& hz, float xi1, float xi2, float a)
    {
        const float phi = xi2 * ENV_TWO_PI;
        const float cosTheta = std::sqrt((1.0f - xi1) / (1.0f + (a * a - 1.0f) * xi1));
        const float sinTheta = std::sqrt(std::max(0.0f, 1.0f - cosTheta * cosTheta));
        hx = std::cos(phi) * sinTheta;
        hy = std::sin(phi) * sinTheta;
        hz = cosTheta;
        // Normalize
        const float len = std::sqrt(hx * hx + hy * hy + hz * hz);
        if (len > 0.0f) {
            hx /= len;
            hy /= len;
            hz /= len;
        }
    }

    void EnvLighting::hemisphereSampleLambert(float& hx, float& hy, float& hz, float xi1, float xi2)
    {
        const float phi = xi2 * ENV_TWO_PI;
        const float cosTheta = std::sqrt(1.0f - xi1);
        const float sinTheta = std::sqrt(xi1);
        hx = std::cos(phi) * sinTheta;
        hy = std::sin(phi) * sinTheta;
        hz = cosTheta;
        // Normalize
        const float len = std::sqrt(hx * hx + hy * hy + hz * hz);
        if (len > 0.0f) {
            hx /= len;
            hy /= len;
            hz /= len;
        }
    }

    float EnvLighting::D_GGX(float NoH, float linearRoughness)
    {
        const float a = NoH * linearRoughness;
        const float k = linearRoughness / (1.0f - NoH * NoH + a * a);
        return k * k * (1.0f / ENV_PI);
    }


    // ----------------------------------------------------------------
    // GGX sample table used by the GPU convolve pass. Mirrors the sample
    // loop in writeGGXRegion (including requiredSamples / zero-padding for
    // below-hemisphere rejections).
    // ----------------------------------------------------------------
    std::vector<float> EnvLighting::generateGGXSampleTable(int numSamples, int specularPower, int sourceTotalPixels)
    {
        const float roughness = 1.0f - std::log2(static_cast<float>(std::max(specularPower, 1))) / 11.0f;
        const float a = roughness * roughness;
        const float pixelsPerSample = static_cast<float>(sourceTotalPixels)
            / static_cast<float>(std::max(numSamples, 1));
        const int requiredSamples = getRequiredSamplesGGX(numSamples, specularPower);

        std::vector<float> table;
        table.reserve(static_cast<size_t>(numSamples) * 4);
        int valid = 0;
        for (int i = 0; i < requiredSamples && valid < numSamples; ++i) {
            float hx, hy, hz;
            hemisphereSampleGGX(hx, hy, hz,
                static_cast<float>(i) / static_cast<float>(requiredSamples),
                Random::radicalInverse(i), a);

            const float NoH = hz;
            const float lx = 2.0f * NoH * hx;
            const float ly = 2.0f * NoH * hy;
            const float lz = 2.0f * NoH * hz - 1.0f;

            if (lz > 0.0f) {
                const float pdf = D_GGX(std::min(1.0f, NoH), a) / 4.0f + 0.001f;
                const float mip = 0.5f * std::log2(pixelsPerSample / pdf);
                table.push_back(lx);
                table.push_back(ly);
                table.push_back(lz);
                table.push_back(mip);
                ++valid;
            }
        }
        while (valid < numSamples) {
            table.push_back(0.0f);
            table.push_back(0.0f);
            table.push_back(0.0f);
            table.push_back(0.0f);
            ++valid;
        }
        return table;
    }

    // ----------------------------------------------------------------
    // Lambert sample table used by the GPU convolve pass. Matches the sample
    // distribution + mip-level math of writeLambertRegion.
    // ----------------------------------------------------------------
    std::vector<float> EnvLighting::generateLambertSampleTable(int numSamples, int sourceTotalPixels)
    {
        const float pixelsPerSample = static_cast<float>(sourceTotalPixels)
            / static_cast<float>(std::max(numSamples, 1));

        std::vector<float> table;
        table.reserve(static_cast<size_t>(numSamples) * 4);
        for (int i = 0; i < numSamples; ++i) {
            float hx, hy, hz;
            hemisphereSampleLambert(hx, hy, hz,
                static_cast<float>(i) / static_cast<float>(numSamples),
                Random::radicalInverse(i));
            const float pdf = hz / ENV_PI;
            const float mip = 0.5f * std::log2(pixelsPerSample / std::max(pdf, 0.001f));
            table.push_back(hx);
            table.push_back(hy);
            table.push_back(hz);
            table.push_back(mip);
        }
        return table;
    }


    // ----------------------------------------------------------------
    // generateAtlas - GPU bake entry point.
    // ----------------------------------------------------------------
    Texture* EnvLighting::generateAtlas(GraphicsDevice* device, Texture* source,
                                        int size, int numReflectionSamples, int numAmbientSamples)
    {
        if (!device || !source) {
            spdlog::error("EnvLighting::generateAtlas: null device or source");
            return nullptr;
        }

        spdlog::info("EnvLighting: generating {}x{} RGBP atlas from {}x{} equirect source",
                     size, size, source->width(), source->height());

        // Destination atlas — empty RGBP-encoded texture; the GPU bake fills it.
        TextureOptions atlasOptions;
        atlasOptions.name = "envAtlas";
        atlasOptions.width = size;
        atlasOptions.height = size;
        atlasOptions.format = PixelFormat::PIXELFORMAT_RGBA8;
        atlasOptions.mipmaps = false;
        atlasOptions.minFilter = FilterMode::FILTER_LINEAR;
        atlasOptions.magFilter = FilterMode::FILTER_LINEAR;
        auto* texture = new Texture(device, atlasOptions);
        texture->setEncoding(TextureEncoding::RGBP);
        texture->upload();

        // HDR cubemap intermediate for GGX/Lambert convolution.
        const int cubemapSize = 256;
        std::shared_ptr<Texture> sourceShared(source, [](Texture*){});
        auto cubemap = equirectToCubemap(device, sourceShared, cubemapSize, false);
        if (!cubemap) {
            spdlog::error("EnvLighting: failed to build HDR cubemap");
            return texture;
        }

        // Layout: mipmap section along the top/diagonal, GGX along the left
        // column of the lower half, Lambert at its fixed sub-rect. Must match
        // the read-time math in the forward shaders.
        struct GGXLevel { int x, y, w, h, specularPower; };
        std::vector<GGXLevel> ggxLevels;
        {
            int rectX = 0, rectY = size / 2, rectW = size / 2, rectH = size / 4;
            for (int i = 1; i <= 6; ++i) {
                if (rectW < 1 || rectH < 1) break;
                const int specularPower = std::max(1, 2048 >> (i * 2));
                ggxLevels.push_back({rectX, rectY, rectW, rectH, specularPower});
                rectY += rectH;
                rectW = std::max(1, rectW / 2);
                rectH = std::max(1, rectH / 2);
            }
        }
        const int lambertRectX = size / 4;
        const int lambertRectY = size / 2 + size / 4;
        const int lambertRectW = size / 8;
        const int lambertRectH = size / 16;

        // Sample tables must outlive the bakeEnvAtlas call since
        // EnvConvolveOp references raw float*.
        const int sourceTotalPixels = cubemapSize * cubemapSize * 6;
        std::vector<std::vector<float>> ggxSamples(ggxLevels.size());
        for (size_t i = 0; i < ggxLevels.size(); ++i) {
            ggxSamples[i] = generateGGXSampleTable(
                numReflectionSamples, ggxLevels[i].specularPower, sourceTotalPixels);
        }
        const auto lambertSamples = generateLambertSampleTable(
            numAmbientSamples, sourceTotalPixels);

        EnvAtlasBakeOptions opts;
        opts.target = std::shared_ptr<Texture>(texture, [](Texture*){});
        opts.encodeRgbp = true;
        opts.decodeSrgb = false;

        opts.reprojectSource = sourceShared;
        opts.reprojectSourceIsCubemap = false;
        {
            const int levels = calcLevels(256) - calcLevels(4);
            int rectX = 0, rectY = 0, rectW = size, rectH = size / 2;
            for (int i = 0; i <= levels; ++i) {
                if (rectW < 1 || rectH < 1) break;
                EnvReprojectRect r;
                r.rectX = rectX; r.rectY = rectY; r.rectW = rectW; r.rectH = rectH;
                r.seamPixels = 1;
                opts.reprojectRects.push_back(r);
                rectX += rectH;
                rectY += rectH;
                rectW = std::max(1, rectW / 2);
                rectH = std::max(1, rectH / 2);
            }
        }

        opts.convolveSource = cubemap;
        opts.convolveSourceIsCubemap = true;
        for (size_t i = 0; i < ggxLevels.size(); ++i) {
            const auto& g = ggxLevels[i];
            EnvConvolveRect r;
            r.rectX = g.x; r.rectY = g.y; r.rectW = g.w; r.rectH = g.h;
            r.seamPixels = 1;
            r.samples = ggxSamples[i].data();
            r.numSamples = numReflectionSamples;
            opts.convolveRects.push_back(r);
        }
        {
            EnvConvolveRect r;
            r.rectX = lambertRectX; r.rectY = lambertRectY;
            r.rectW = lambertRectW; r.rectH = lambertRectH;
            r.seamPixels = 1;
            r.samples = lambertSamples.data();
            r.numSamples = numAmbientSamples;
            opts.convolveRects.push_back(r);
        }

        bakeEnvAtlas(device, opts);

        spdlog::info("EnvLighting: atlas generated ({}x{}, RGBP)", size, size);
        return texture;
    }

    // ----------------------------------------------------------------
    // generateSkyboxCubemap
    // EnvLighting.generateSkyboxCubemap()
    // Creates a high-res cubemap from equirectangular HDR source.
    // ----------------------------------------------------------------
    Texture* EnvLighting::generateSkyboxCubemap(GraphicsDevice* device, Texture* source, int size)
    {
        if (!device || !source) {
            spdlog::warn("EnvLighting::generateSkyboxCubemap: null device or source");
            return nullptr;
        }

        const auto* srcData = static_cast<const float*>(source->getLevel(0));
        if (!srcData) {
            spdlog::warn("EnvLighting::generateSkyboxCubemap: source has no pixel data");
            return nullptr;
        }

        const int srcW = static_cast<int>(source->width());
        const int srcH = static_cast<int>(source->height());

        // default size = source.width / 4 for equirect
        if (size <= 0) {
            size = srcW / 4;
        }
        // Clamp to reasonable range
        size = std::clamp(size, 4, 4096);

        spdlog::info("EnvLighting: generating {}x{} skybox cubemap from {}x{} equirect source",
                     size, size, srcW, srcH);

        const size_t facePixels = static_cast<size_t>(size) * static_cast<size_t>(size);
        const size_t faceBytes = facePixels * 4; // RGBA8

        // For each face, compute the direction for each pixel, sample the equirect source,
        // and convert from linear HDR to sRGB RGBA8.
        TextureOptions options;
        options.name = "skyboxCubemap";
        options.width = size;
        options.height = size;
        options.format = PixelFormat::PIXELFORMAT_RGBA8;
        options.cubemap = true;
        options.mipmaps = false;
        options.minFilter = FilterMode::FILTER_LINEAR;
        options.magFilter = FilterMode::FILTER_LINEAR;

        auto* texture = new Texture(device, options);
        texture->setEncoding(TextureEncoding::RGBP);

        for (int face = 0; face < 6; ++face) {
            std::vector<uint8_t> faceData(faceBytes);

            for (int py = 0; py < size; ++py) {
                for (int px = 0; px < size; ++px) {
                    // Compute face UV (pixel center)
                    const float u = (static_cast<float>(px) + 0.5f) / static_cast<float>(size);
                    const float v = (static_cast<float>(py) + 0.5f) / static_cast<float>(size);

                    // Face UV -> world direction
                    float dx, dy, dz;
                    faceUvToDir(face, u, v, dx, dy, dz);

                    // Direction -> equirect UV
                    float srcU, srcV;
                    dirToEquirectUv(dx, dy, dz, srcU, srcV);

                    // Wrap horizontally, clamp vertically
                    srcU = srcU - std::floor(srcU);
                    srcV = std::clamp(srcV, 0.0f, 1.0f);

                    // Bilinear sample from source equirect (RGBA32F)
                    const float fx = srcU * static_cast<float>(srcW - 1);
                    const float fy = srcV * static_cast<float>(srcH - 1);

                    const int x0 = std::clamp(static_cast<int>(std::floor(fx)), 0, srcW - 1);
                    const int y0 = std::clamp(static_cast<int>(std::floor(fy)), 0, srcH - 1);
                    const int x1 = (x0 + 1) % srcW;
                    const int y1 = std::min(y0 + 1, srcH - 1);

                    const float sx = fx - static_cast<float>(x0);
                    const float sy = fy - static_cast<float>(y0);

                    auto pixel = [&](int ppx, int ppy) -> const float* {
                        return &srcData[(ppy * srcW + ppx) * 4];
                    };

                    const float* p00 = pixel(x0, y0);
                    const float* p10 = pixel(x1, y0);
                    const float* p01 = pixel(x0, y1);
                    const float* p11 = pixel(x1, y1);

                    float r = 0.0f, g = 0.0f, b = 0.0f;
                    for (int c = 0; c < 3; ++c) {
                        const float top = p00[c] * (1.0f - sx) + p10[c] * sx;
                        const float bot = p01[c] * (1.0f - sx) + p11[c] * sx;
                        const float val = top * (1.0f - sy) + bot * sy;
                        if (c == 0) r = val;
                        else if (c == 1) g = val;
                        else b = val;
                    }

                    // Tonemap: clamp HDR to [0, 1] with simple reinhard
                    // Upstream uses numSamples=1024 reprojectTexture which is essentially
                    // a direct copy. The skybox shader applies exposure + tonemapping at runtime,
                    // so we store linear clamped to displayable range.
                    // Use RGBP encoding for HDR preservation (same as envAtlas).
                    const auto encoded = encodeRGBP(r, g, b);

                    const size_t offset = (static_cast<size_t>(py) * size + px) * 4;
                    faceData[offset + 0] = encoded[0];
                    faceData[offset + 1] = encoded[1];
                    faceData[offset + 2] = encoded[2];
                    faceData[offset + 3] = encoded[3];
                }
            }

            texture->setLevelData(0, faceData.data(), faceData.size(), face);
        }

        texture->upload();

        spdlog::info("EnvLighting: skybox cubemap generated successfully ({}x{} per face, RGBP)", size, size);

        return texture;
    }
}
