#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026 Arnis Lektauers
#
# Created by Arnis Lektauers on 07.10.2026
#
"""Compiles every Slang program into one embedded header: slang_shader_bundle.h.

For each engine/shaders/slang/programs/<name>.slang the entry points are read from its
`[shader("vertex")]` / `[shader("fragment")]` / `[shader("compute")]` attributes and the
program is compiled with slangc, once per target this build's backends take: `metal`
(one MSL source holding every entry point, compiled by the Metal backend at run time the
way its hand-written MSL is) and `spirv` (one module per entry point, the entry point
named `main` as the Vulkan pipeline binds it). Matrices are read ROW-major on every target, so
a shader writes `mul(v, M)` for the engine's column-major M * v (see SlangCompiler).
The generated bindings.slang is on the include path, and its text is embedded too so a
runtime override compile can serve it from memory.

The header holds one `Program` per source with its name, entry point names and the code
for each target that was built (empty where it was not), and `findProgram(name)`.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# `[shader("stage")]`, any further attributes (a compute entry's `[numthreads(...)]`), the
# return type, the name.
ENTRY_RE = re.compile(r'\[shader\("(vertex|fragment|compute)"\)\]\s*(?:\[[^\]]*\]\s*)*[\w<>:]+\s+(\w+)\s*\(')
# `// @variant <name>: DEFINE=value DEFINE2` — one compile per line, with those defines; a
# program with no such line is compiled once, as variant "".
VARIANT_RE = re.compile(r'^//\s*@variant\s+([\w.-]+)\s*:(.*)$', re.MULTILINE)


def variants_of(source: str) -> list[tuple[str, list[str]]]:
    found = [(m.group(1), m.group(2).split()) for m in VARIANT_RE.finditer(source)]
    return found if found else [("", [])]
STAGE_FLAG = {"vertex": "vertex", "fragment": "fragment", "compute": "compute"}


def run(command: list[str]) -> None:
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise RuntimeError(f"command failed: {' '.join(command)}")
    if result.stderr.strip():
        # slangc warnings go to stderr with a zero exit; keep them visible in the build log.
        sys.stderr.write(result.stderr)


def camel(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[-_]", name))


def words_literal(data: bytes) -> str:
    if len(data) % 4:
        raise RuntimeError("SPIR-V is not a whole number of words")
    words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
    lines = []
    for i in range(0, len(words), 8):
        lines.append("    " + ", ".join(f"0x{w:08x}u" for w in words[i:i + 8]) + ",")
    return "\n".join(lines)


def raw_string(text: str) -> str:
    delimiter = "VTSLANG"
    while f"){delimiter}\"" in text:
        delimiter += "_"
    return f'R"{delimiter}({text}){delimiter}"'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--slangc", required=True, type=Path)
    parser.add_argument("--source-dir", required=True, type=Path, help="engine/shaders/slang")
    parser.add_argument("--bindings", required=True, type=Path, help="the generated bindings.slang")
    parser.add_argument("--targets", required=True, help="comma-separated: metal, spirv")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--work-dir", required=True, type=Path)
    args = parser.parse_args()

    targets = [t for t in args.targets.split(",") if t]
    for target in targets:
        if target not in ("metal", "spirv"):
            raise RuntimeError(f"unknown target {target}")
    args.work_dir.mkdir(parents=True, exist_ok=True)
    modules_dir = args.source_dir / "modules"
    programs = sorted((args.source_dir / "programs").glob("*.slang"))

    common = [str(args.slangc), "-I", str(modules_dir), "-I", str(args.bindings.parent),
              "-matrix-layout-row-major"]

    out = [
        "// Generated by tools/generate_slang_bundle.py from engine/shaders/slang. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace visutwin::canvas::slang_generated",
        "{",
        "    struct Program",
        "    {",
        "        const char* name;",
        "        const char* variant;        // \"\" for a program without @variant lines",
        "        const char* vertexEntry;    // empty when the program has no such stage",
        "        const char* fragmentEntry;",
        "        const char* computeEntry;",
        "        const char* metalSource;    // MSL with every entry point; empty when metal was not built",
        "        const uint8_t* metalLibrary; // the same compiled to a metallib by Apple's compiler; null when not built",
        "        size_t metalLibraryBytes;",
        "        const uint32_t* vertexSpirv;",
        "        size_t vertexSpirvWords;",
        "        const uint32_t* fragmentSpirv;",
        "        size_t fragmentSpirvWords;",
        "        const uint32_t* computeSpirv;",
        "        size_t computeSpirvWords;",
        "    };",
        "",
        f"    inline constexpr char kBindingsSlang[] = {raw_string(args.bindings.read_text())};",
        "",
    ]
    entries = []
    for program in programs:
        name = program.stem
        source = program.read_text()
        found = {stage: entry for stage, entry in ENTRY_RE.findall(source)}
        if not found:
            raise RuntimeError(f"{program}: no [shader(...)] entry points found")
        for variant, defines in variants_of(source):
            define_flags = []
            for define in defines:
                define_flags += ["-D" + define]
            ident = "k" + camel(name) + (camel(variant.replace(".", "_")) if variant else "")
            stem = name + (f"@{variant}" if variant else "")
            fields = {"metalSource": '""', "metalLibrary": "nullptr, 0"}
            spirv = {}
            if "metal" in targets:
                msl_path = args.work_dir / f"{stem}.metal"
                command = common + define_flags + ["-DVT_TARGET_METAL"] + [str(program), "-target", "metal", "-o", str(msl_path)]
                for stage, entry in found.items():
                    command += ["-entry", entry, "-stage", STAGE_FLAG[stage]]
                run(command)
                out.append(f"    inline constexpr char {ident}Msl[] = {raw_string(msl_path.read_text())};")
                fields["metalSource"] = f"{ident}Msl"
                # The same MSL compiled by Apple's compiler, so the Metal backend loads a library
                # instead of compiling MSL on first use. Compiled HERE, with fast math on, as
                # MetalShader compiles source at run time, not through slangc's metallib
                # target: slangc invokes the compiler with options of its own, and the library it
                # built rounded differently from the runtime compile of the very same MSL (TAA
                # by a count over 44,000 pixels), so the bundle and an override disagreed.
                air_path = args.work_dir / f"{stem}.air"
                lib_path = args.work_dir / f"{stem}.metallib"
                run(["xcrun", "-sdk", "macosx", "metal", "-ffast-math", "-c", str(msl_path), "-o", str(air_path)])
                run(["xcrun", "-sdk", "macosx", "metallib", str(air_path), "-o", str(lib_path)])
                data = lib_path.read_bytes()
                if data[:4] != b"MTLB":
                    raise RuntimeError(f"{lib_path}: not a metallib")
                out.append(f"    inline constexpr uint8_t {ident}MetalLib[] = {{")
                for i in range(0, len(data), 24):
                    out.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
                out.append("    };")
                fields["metalLibrary"] = f"{ident}MetalLib, sizeof({ident}MetalLib)"
            if "spirv" in targets:
                for stage, entry in found.items():
                    spv_path = args.work_dir / f"{stem}.{stage}.spv"
                    run(common + define_flags + [str(program), "-target", "spirv", "-entry", entry,
                                                 "-stage", STAGE_FLAG[stage], "-o", str(spv_path)])
                    data = spv_path.read_bytes()
                    if data[:4] != b"\x03\x02\x23\x07":
                        raise RuntimeError(f"{spv_path}: not SPIR-V")
                    array = f"{ident}{camel(stage)}Spirv"
                    out.append(f"    inline constexpr uint32_t {array}[] = {{")
                    out.append(words_literal(data))
                    out.append("    };")
                    spirv[stage] = array
            entry_names = {stage: f'"{found[stage]}"' if stage in found else '""'
                           for stage in ("vertex", "fragment", "compute")}
            spv_fields = []
            for stage in ("vertex", "fragment", "compute"):
                if stage in spirv:
                    spv_fields.append(f"{spirv[stage]}, sizeof({spirv[stage]}) / sizeof(uint32_t)")
                else:
                    spv_fields.append("nullptr, 0")
            entries.append(
                f'        Program{{"{name}", "{variant}", {entry_names["vertex"]}, {entry_names["fragment"]}, '
                f'{entry_names["compute"]}, {fields["metalSource"]}, {fields["metalLibrary"]}, {", ".join(spv_fields)}}},')
            out.append("")

    out += [
        f"    inline constexpr std::array<Program, {len(entries)}> kPrograms = {{{{",
        *entries,
        "    }};",
        "",
        "    inline const Program* findProgram(const std::string_view name, const std::string_view variant = {})",
        "    {",
        "        for (const auto& program : kPrograms) {",
        "            if (name == program.name && variant == program.variant) {",
        "                return &program;",
        "            }",
        "        }",
        "        return nullptr;",
        "    }",
        "}",
        "",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out))


if __name__ == "__main__":
    main()
