#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026 Arnis Lektauers
#
# Created by Arnis Lektauers on 07.10.2026
#
"""Writes bindings.slang from the binding table (engine/src/platform/graphics/shaderBindings.h).

Each row becomes one declaration macro carrying BOTH annotations a Slang module needs:
`register(tN)` / `register(sN)`, which decides the Metal slot (Metal ignores
`vk::binding`, and a sampler index above 15 fails Apple's compiler), and
`[[vk::binding(binding, set)]]`, which decides the Vulkan and WGSL one. A Slang module
writes `VT_DECLARE_baseColorMap` instead of spelling either number. Combined-sampler rows
also get a companion sampler declaration on the Metal sampler slot their map carries
(1 + the row's index among the maps that own a sampler, as MetalTextureBinder binds them).

Nothing consumes this file yet: it is the single source the Slang modules will declare
their bindings from (phase 2 of the single-source shader migration).
"""
from __future__ import annotations

import argparse
from pathlib import Path

from shader_bindings import MATERIAL_SET, SCENE_SET, BindingRow, read_bindings

SLANG_TYPE = {
    "Tex2D": "Texture2D",
    "TexCube": "TextureCube",
    "Tex2DArray": "Texture2DArray",
}


def declaration(row: BindingRow, set_index: int, sampler_slot: int | None) -> list[str]:
    lines = [f"// {row.name}: Metal {'sampler' if row.type == 'Sampler' else 'texture'} "
             f"{row.metal_slot if row.metal_slot >= 0 else '(constexpr)'}"
             f"{' (vertex)' if 0 <= row.metal_slot >= 100 else ''}"
             f"{', Vulkan set %d binding %d' % (set_index, row.vk_binding) if row.vk_binding >= 0 else ', Metal only'}"]
    vk = f"[[vk::binding({row.vk_binding}, {set_index})]] " if row.vk_binding >= 0 else ""
    if row.type == "Sampler":
        if row.metal_slot >= 0:
            lines.append(f"#define VT_DECLARE_{row.name} {vk}SamplerState {row.name} : register(s{row.metal_slot});")
        else:
            lines.append(f"#define VT_DECLARE_{row.name} {vk}SamplerState {row.name};")
        return lines
    metal_slot = row.metal_slot - 100 if row.metal_slot >= 100 else row.metal_slot
    lines.append(f"#define VT_DECLARE_{row.name} {vk}{SLANG_TYPE[row.type]} {row.name} : register(t{metal_slot});")
    if sampler_slot is not None:
        # Vulkan reads the map through a combined image sampler at the same binding; the
        # companion is the Metal sampler slot. The combined form Slang emits per target
        # is decided when the modules are written.
        lines.append(f"#define VT_DECLARE_{row.name}Sampler {vk}SamplerState {row.name}Sampler : register(s{sampler_slot});")
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bindings", required=True, type=Path, help="shaderBindings.h")
    parser.add_argument("--output", required=True, type=Path, help="bindings.slang to write")
    args = parser.parse_args()

    material, scene = read_bindings(args.bindings)
    out = [
        "// Generated by tools/generate_shader_bindings.py from",
        f"// {args.bindings.name}. Do not edit: change the table and rebuild.",
        "//",
        "// Every binding of both backends, as one Slang declaration macro each. register()",
        "// is the Metal slot; [[vk::binding]] the Vulkan and WGSL one. See the header.",
        "",
        "// ---- Material textures (Vulkan set 1, quad inputs 0..5 on both backends) ----",
    ]
    own_sampler_index = 0
    for row in material:
        sampler_slot = None
        if row.own_sampler:
            own_sampler_index += 1
            sampler_slot = own_sampler_index
        out += declaration(row, MATERIAL_SET, sampler_slot)
    out += ["", "// ---- Scene textures (Vulkan set 3) ----"]
    for row in scene:
        out += declaration(row, SCENE_SET, None)
    out.append("")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out))


if __name__ == "__main__":
    main()
